services:
    voicescribe-pro:
        container_name: development-voicescribe-pro
        build:
            context: .
            target: development
        ports:
            - "8000:8000"
        volumes:
            - .:/app # Mount to /app to match WORKDIR
            - /app/tmp # Exclude tmp directory from mount
        environment:
            - GO_ENV=development
            - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
